# Netlify Configuration for OTAI
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command to run
  command = "npm run build"
  
  # Directory with the static content to deploy
  publish = "dist"
  
  # Node.js version to use
  [build.environment]
    NODE_VERSION = "22.11.0"

# Redirect rules for SPA (Single Page Application)
# This ensures that all routes work correctly with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these should be set in Netlify UI for security)
# VITE_GEMINI_API_KEY = "your-api-key-here"
